CREATE DATABASE GufosBD

USE GufosBD
CREATE TABLE TipoUsuario
(
	IdTipo INT PRIMARY KEY IDENTITY,
	Titulo VARCHAR(255) UNIQUE NOT NULL,
);


CREATE TABLE Usuario
(
	IdUsuario INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(255) NOT NULL,
	CPF VARCHAR(11),
	Email VARCHAR(255) UNIQUE NOT NULL,
	Senha VARCHAR(255) NOT NULL,
	Ativo BIT DEFAULT 1,
	IdTIpoUsuario INT FOREIGN KEY REFERENCES TipoUsuario(IdTipo)
);


CREATE TABLE Categoria
(
	IdCategoria INT PRIMARY KEY NOT NULL,
	Titulo VARCHAR(2255) UNIQUE NOT NULL,
	Ativo BIT DEFAULT 1
);


CREATE TABLE Localizacao
(
	IdLocalizacao INT PRIMARY KEY IDENTITY NOT NULL,
	CNPJ CHAR(14) UNIQUE NOT NULL,
	RazaoSocial VARCHAR(200) UNIQUE NOT NULL,
	Endereco VARCHAR(255) NOT NULL
);


CREATE TABLE Evento
(
	IdEventos INT PRIMARY KEY IDENTITY NOT NULL,
	Titulo VARCHAR(255) UNIQUE NOT NULL,
	Descricao VARCHAR(100),
	DataEvento DATETIME,
	AcessoLivre BIT DEFAULT 1,
	IdCategoria INT FOREIGN KEY REFERENCES Categoria(idCategoria),
	IdLocalizacao INT FOREIGN KEY REFERENCES Localizacao(idLocalizacao),
	Ativo BIT DEFAULT 1
);

CREATE TABLE PresencaEvento
(
	IdPresenca INT PRIMARY KEY IDENTITY NOT NULL,
	IdEvento INT FOREIGN KEY REFERENCES Evento(IdEventos),
	IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario),
	PresencaStatus VARCHAR(255) NOT NULL
);